// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartKunu.Server.Data;

#nullable disable

namespace SmartKunu.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartKunu.Server.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReporterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WasteCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("SmartKunu.Server.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Guidelines")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PickupDates")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RouteInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WasteCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Guidelines = "CMC will reject mixed polythene bags",
                            Municipality = "Colombo Municipal Council",
                            PickupDates = "Every Monday & Thursday",
                            RouteInfo = "Galle Road Corridor",
                            Ward = "Colombo 03 - Kollupitiya",
                            WasteCategory = "Perishable Organic"
                        },
                        new
                        {
                            Id = 2,
                            Guidelines = "Clean & dry plastics only",
                            Municipality = "Colombo Municipal Council",
                            PickupDates = "Every Wednesday",
                            RouteInfo = "Dharmapala Mawatha Sector",
                            Ward = "Colombo 07 - Cinnamon Gardens",
                            WasteCategory = "Recyclable Plastics"
                        },
                        new
                        {
                            Id = 3,
                            Guidelines = "Flatten all cardboard cartons",
                            Municipality = "Dehiwala-Mount Lavinia MC",
                            PickupDates = "Every Tuesday",
                            RouteInfo = "Vandervort Place & Station Rd",
                            Ward = "Dehiwala Ward 4",
                            WasteCategory = "Paper/Cardboard"
                        },
                        new
                        {
                            Id = 4,
                            Guidelines = "Includes appliances, batteries & scrap metal",
                            Municipality = "Dehiwala-Mount Lavinia MC",
                            PickupDates = "Last Friday of the month",
                            RouteInfo = "Ward 4 Community Drop",
                            Ward = "Dehiwala Ward 4",
                            WasteCategory = "Electronic Waste"
                        },
                        new
                        {
                            Id = 5,
                            Guidelines = "Only biodegradable waste collected",
                            Municipality = "Kaduwela Municipal Council",
                            PickupDates = "Monday, Wednesday, Friday",
                            RouteInfo = "Main Road Zone",
                            Ward = "Battaramulla Ward 2",
                            WasteCategory = "Perishable Organic"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
